import localFont from "next/font/local";
import "./globals.css";
import Header from "./header";
import { Footer } from "./footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header />
        <div className="bg-gray-50">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
